version: '3.7'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=flashgameratings
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=flashgameratings_development
    ports:
      - 5433:5432
    volumes:
      - ~/docker/volumes/flashgameratings/postgres:/var/lib/postgresql/data
